import copy

ALPHABET_DICT = {
    "A": "a",
    "B": "bê",
    "C": "xê",
    "D": "đê",
    "Đ": "đê",
    "E": "e",
    "F": "ép",
    "J": "di",
    "G": "gờ",
    "H": "hát",
    "I": "y",
    "K": "ca",
    "L": "lờ",
    "M": "mờ",
    "N": "nờ",
    "O": "o",
    "P": "pê",
    "Q": "quy",
    "R": "rờ",
    "S": "ét",
    "T": "tê",
    "U": "u",
    "V": "vê",
    "X": "ích",
    "Y": "y",
    "W": "vê kép",
    "Z": "dét",
    "a": "a",
    "b": "bê",
    "c": "xê",
    "d": "đê",
    "đ": "đê",
    "e": "e",
    "f": "ép",
    "j": "di",
    "g": "gờ",
    "h": "hát",
    "i": "y",
    "k": "ca",
    "l": "lờ",
    "m": "mờ",
    "n": "nờ",
    "o": "o",
    "p": "pê",
    "q": "quy",
    "r": "rờ",
    "s": "ét",
    "t": "tê",
    "u": "u",
    "v": "vê",
    "x": "ích",
    "y": "y",
    "w": "vê kép",
    "z": "dét"
}

NUMBER_DICT = {
    "1": "một",
    "2": "hai",
    "3": "ba",
    "4": "bốn",
    "5": "năm",
    "6": "sáu",
    "7": "bảy",
    "8": "tám",
    "9": "chín",
    "0": "không",
}

SYMBOL_DICT = {
    "!": "chấm than",
    "~": "xấp xỉ",
    "@": "a còng",
    "#": "thăng",
    "$": "đô la",
    "%": "phần trăm",
    "^": "mũ",
    "&": "và",
    "*": "sao",
    "-": "gạch ngang",
    "_": "gạch dưới",
    "+": "cộng",
    "=": "bằng",
    ":": "hai chấm",
    ";": "chấm phẩy",
    "'": "nháy đơn",
    "`": "nháy đơn",
    '"': "nháy kép",
    "|": "gạch dọc",
    "/": "gạch chéo",
    "\\": "gạch chéo",
    ",": "phẩy",
    ".": "chấm",
    "<": "nhỏ hơn",
    ">": "lớn hơn",
    "?": "hỏi chấm",
    " ": "cách",
    "π": "pi",
}

NON_SILENT_SYMBOL_LIST = list("~@#$%^&*+=/\\<>π")
NON_SILENT_SYMBOL_DICT = {s : SYMBOL_DICT[s] for s in NON_SILENT_SYMBOL_LIST}
SILENT_SYMBOL_LIST = [s for s in SYMBOL_DICT if s not in NON_SILENT_SYMBOL_DICT]

BASIC_MATH_OPERATOR_DICT = {
    "<=>": "tương đương",
    "=>": "suy ra",
    "+": "cộng",
    "-": "trừ",
    "*": "nhân",
    " x ": "nhân",
    "/": "trên",
    "^": "mũ",
    "%": "phần trăm",
    "<": "nhỏ hơn",
    ">": "lớn hơn",
    "?": "hỏi chấm",
    "=": "bằng",
    "~": "xấp xỉ",
}

BRACKETS_MATH_OPERATOR_DICT = {
    "|": "",
    "(": "mở ngoặc",
    "[": "mở ngoặc",
    "{": "mở ngoặc",
    ")": "đóng ngoặc",
    "]": "đóng ngoặc",
    "}": "đóng ngoặc",
}

FULL_MATH_OPERATOR_DICT = {
    **BASIC_MATH_OPERATOR_DICT,
    **BRACKETS_MATH_OPERATOR_DICT,
}

BASIC_NUMBER_OPERATOR_DICT = copy.deepcopy(BASIC_MATH_OPERATOR_DICT)
BASIC_NUMBER_OPERATOR_DICT.update({
    "/": "phần"
})

EMAIL_AND_URL_COMPONENT_DICT = {
    # --- Protocols & Prefixes ---
    "https": "hát tê tê pê ét",
    "http": "hát tê tê pê",
    "www": "vê kép vê kép vê kép",
    "ftp": "ép tê pê",
    "mailto": "meo tu",
    
    # --- Top-Level Domains (TLDs) ---
    "ai": "ây ai",
    "app": "áp",
    "asia": "a si a",
    "biz": "bít",
    "club": "cờ lấp",
    "co": "cô",
    "com": "com",
    "dev": "đép",
    "doc": "đóc",
    "docs": "đóc",
    "edu": "e đu",
    "gov": "gờ o vê",
    "info": "in pho",
    "io": "i ô",
    "live": "lai",
    "lite": "lai",
    "net": "nét",
    "org": "o rờ gờ",
    "pro": "pờ rô",
    "shop": "sóp",
    "store": "sờ to",
    "tv": "ti vi",
    "vi": "vi",
    "vn": "vi en",
    "vtv": "vê tê vê",
    "xyz": "ích y dét",
    "src": "ét rờ xê",
    "util": "un tiu",
    "utils": "un tiu",
    "url": "u rờ lờ",

    # --- Email & Services ---
    "account": "ạc cao",
    "accounts": "ạc cao",
    "admin": "át min",
    "contact": "con tắc",
    "email": "y meo",
    "gmail": "gờ meo",
    "mail": "meo",
    "inbox": "in bóc",
    "help": "hép",
    "home": "hôm",
    "hotmail": "hót meo",
    "id": "ai đi",
    "jobs": "dóp",
    "link": "linh",
    "login": "lốc in",
    "logout": "lốc ao",
    "marketing": "ma két tinh",
    "news": "niu",
    "noreply": "nâu ríp lai",
    "outlook": "ao lúc",
    "page": "pết",
    "password": "pát uốt",
    "register": "re gít tơ",
    "sales": "sêu",
    "signout": "sai ao",
    "signup": "sai ắp",
    "site": "sai",
    "support": "súp pót",
    "tele": "te le",
    "username": "iu dơ nêm",
    "user": "iu dơ",
    "web": "guép",
    "yahoo": "da hu",
    "localhost": "lo cồ hót",
    
    # --- Common File Types & Tech Terms ---
    "api": "ây pi ai",
    "apk": "a pê ca",
    "config": "con phích",
    "css": "xê ét ét",
    "cpp": "xê pê pê",
    "java": "da va",
    "data": "đa ta",
    "database": "đa ta bây",
    "doc": "đóc",
    "docx": "đóc ích",
    "domain": "đô men",
    "exe": "e ích e",
    "excel": "ích xeo",
    "faq": "ép ây kiu",
    "gif": "gíp",
    "html": "hát tê mờ lờ",
    "jpeg": "di pê e gờ",
    "jpg": "di pê gờ",
    "js": "di ét",
    "json": "di son",
    "media": "me đi a",
    "mp3": "mờ pê ba",
    "mp4": "mờ pê bốn",
    "online": "on lai",
    "pdf": "pê đê ép",
    "php": "pê hát pê",
    "png": "pê nờ gờ",
    "ppt": "pê pê tê",
    "py": "py",
    "pptx": "pê pê tê ích",
    "rar": "ra",
    "server": "sơ vơ",
    "studio": "sờ tu đi ô",
    "svg": "ét vê gờ",
    "system": "síp từm",
    "tech": "tếch",
    "token": "tô cần",
    "wiki": "uy ki",
    "xls": "ích lờ ét",
    "xlsx": "ích lờ ét ích",
    "xml": "ích mờ lờ",
    "zip": "díp",
    
    # --- Social Media & Brands ---
    "facebook": "phây búc",
    "google": "gu gồ",
    "github": "gít hắp",
    "instagram": "in ta gờ ram",
    "microsoft": "mai cờ rô sốp",
    "tiktok": "tíc tốc",
    "youtube": "du túp",
    "zalo": "da lô"
}

WORD_BREAK_DICT = {
    "admin": "admin",
    "baocao": "báo cáo",
    "baocaochitiet": "báo cáo chi tiết",
    "baocaohoatdong": "báo cáo hoạt động",
    "baogia": "báo giá",
    "baohanh": "bảo hành",
    "baohiem": "bảo hiểm",
    "baomat": "bảo mật",
    "baovetaisan": "bảo vệ tài sản",
    "banhang": "bán hàng",
    "bantin": "bản tin",
    "bantinthongminh": "bản tin thông minh",
    "bank": "bank",
    "bocongan": "bộ công an",
    "bosung": "bổ sung",
    "bosunghoso": "bổ sung hồ sơ",
    "caitien": "cải tiến",
    "camket": "cam kết",
    "canhan": "cá nhân",
    "canhsat": "cảnh sát",
    "canhsatgt": "cảnh sát gt",
    "caplai": "cấp lại",
    "capnhat": "cập nhật",
    "capnhatvay": "cập nhật vay",
    "cauhoi": "câu hỏi",
    "ceo": "ceo",
    "hoatdong": "hoạt động",
    "chamsoc": "chăm sóc",
    "chamsockhachhang": "chăm sóc khách hàng",
    "khachhang": "khách hàng",
    "chienthuat": "chiến thuật",
    "chinhphu": "chính phủ",
    "chinhthuc": "chính thức",
    "chinhanh": "chi nhánh",
    "chuduan": "chủ dự án",
    "chungcu": "chung cư",
    "chungtu": "chứng từ",
    "chuyenkhoan": "chuyển khoản",
    "chuyenmon": "chuyên môn",
    "chuyennghiep": "chuyên nghiệp",
    "chuyenphat": "chuyển phát",
    "chuyensau": "chuyên sâu",
    "chuyenvien": "chuyên viên",
    "congchung": "công chứng",
    "congdan": "công dân",
    "congdong": "cộng đồng",
    "congty": "công ty",
    "congviec": "công việc",
    "cophieu": "cổ phiếu",
    "cuahang": "cửa hàng",
    "cuocsong": "cuộc sống",
    "dangkiem": "đăng kiểm",
    "dangky": "đăng ký",
    "dangkykhoahoc": "đăng ký khóa học",
    "dangkysukien": "đăng ký sự kiện",
    "sukien": "sự kiện",
    "khoahoc": "khoa học",
    "dautu": "đầu tư",
    "dichvu": "dịch vụ",
    "dichvutudo": "dịch vụ tự do",
    "tudo": "tự cdo",
    "dieuchinh": "điều chỉnh",
    "dieuphoi": "điều phối",
    "dieutra": "điều tra",
    "dieuhanh": "điều hành",
    "doanhnghiep": "doanh nghiệp",
    "doimoi": "đổi mới",
    "doitac": "đối tác",
    "doithu": "đối thủ",
    "donggop": "đóng góp",
    "donhang": "đơn hàng",
    "dotxuat": "đột xuất",
    "docquyen": "độc quyền",
    "duan": "dự án",
    "dulich": "du lịch",
    "dulieu": "dữ liệu",
    "duongbo": "đường bộ",
    "duyet": "duyệt",
    "duyethoso": "duyệt hồ sơ",
    "duyetvay": "duyệt vay",
    "giahan": "gia hạn",
    "giaidap": "giải đáp",
    "giaimay": "giải máy",
    "giaingay": "giải ngay",
    "giaingan": "giải ngân",
    "giaingansao": "giải ngân sao",
    "giaiphap": "giải pháp",
    "giaiphong": "giải phóng",
    "giaiquyet": "giải quyết",
    "giaodich": "giao dịch",
    "giaoduc": "giáo dục",
    "giaohoa": "giao hòa",
    "giaothong": "giao thông",
    "giapha": "gia phả",
    "giayphep": "giấy phép",
    "giaytotuythan": "giấy tờ tùy thân",
    "giayto": "giấy tờ",
    "gopy": "góp ý",
    "gopyhientruong": "góp ý hiện trường",
    "hientruong": "hiện trường",
    "hiephoi": "hiệp hội",
    "hoadon": "hóa đơn",
    "hoanthanhtailieu": "hoàn thành tài liệu",
    "hoanthanh": "hoàn thành",
    "tailieu": "tài liệu",
    "hocbong": "học bổng",
    "hocvien": "học viên",
    "hoidap": "hỏi đáp",
    "hoidapluat": "hỏi đáp luật",
    "hoithao": "hội thảo",
    "hoitruong": "hội trường",
    "hoivien": "hội viên",
    "hopdong": "hợp đồng",
    "hopdongvay": "hợp đồng vay",
    "hoptac": "hợp tác",
    "hopthu": "hộp thư",
    "homthu": "hòm thư",
    "hoso": "hồ sơ",
    "hosogoc": "hồ sơ gốc",
    "hosoluat": "hồ sơ luật",
    "hosovay": "hồ sơ vay",
    "hotro": "hỗ trợ",
    "hotrogtvt": "hỗ trợ gtvt",
    "hotrokithuat": "hỗ trợ kĩ thuật",
    "hotrokythuat": "hỗ trợ kỹ thuật",
    "kithuat": "kĩ thuật",
    "kythuat": "kỹ thuật",
    "hotrokhachhang": "hỗ trợ khách hàng",
    "hotrovip": "hỗ trợ vip",
    "huongdan": "hướng dẫn",
    "ketoan": "kế toán",
    "ketqua": "kết quả",
    "khachhang": "khách hàng",
    "khachsan": "khách sạn",
    "khaithongtin": "khai thông tin",
    "thongtin": "thông tin",
    "khampha": "khám phá",
    "khancap": "khẩn cấp",
    "khangcao": "kháng cáo",
    "khieunai": "khiếu nại",
    "khoahoc": "khoa học",
    "khoanvay": "khoản vay",
    "khoinghiep": "khởi nghiệp",
    "khoiphucmatkhau": "khôi phục mật khẩu",
    "matkhau": "mật khẩu",
    "khongtruycapduoc": "không truy cập được",
    "truycap": "truy cập",
    "khuyenmai": "khuyến mãi",
    "kiemdinh": "kiểm định",
    "kiemduyet": "kiểm duyệt",
    "kiemsoat": "kiểm soát",
    "kiemtra": "kiểm tra",
    "kiemtrahoso": "kiểm tra hồ sơ",
    "kiemtoan": "kiểm toán",
    "kinhdoanh": "kinh doanh",
    "kichhoat": "kích hoạt",
    "kythuat": "kỹ thuật",
    "lienhe": "liên hệ",
    "lienhemuasam": "liên hệ mua sắm",
    "lienket": "liên kết",
    "lienlac": "liên lạc",
    "luat": "luật",
    "luatgiaothong": "luật giao thông",
    "luatsu": "luật sư",
    "luatsuphaply": "luật sư pháp lý",
    "phaply": "pháp lý",
    "quanly": "quản lý",
    "tiepthi": "tiếp thị",
    "minhbach": "minh bạch",
    "moitruong": "môi trường",
    "muaban": "mua bán",
    "muahang": "mua hàng",
    "muasam": "mua sắm",
    "nganhang": "ngân hàng",
    "nghethuat": "nghệ thuật",
    "nghiencuu": "nghiên cứu",
    "ngonluan": "ngôn luận",
    "nguoidung": "người dùng",
    "nhacungcap": "nhà cung cấp",
    "cungcap": "cung cấp",
    "nhadautu": "nhà đầu tư",
    "nhanhchong": "nhanh chóng",
    "nhansu": "nhân sự",
    "nhom": "nhóm",
    "nop": "nộp",
    "nopphat": "nộp phạt",
    "tructuyen": "trực tuyến",
    "phananh": "phản ánh",
    "phandoi": "phản đối",
    "phanhoi": "phản hồi",
    "phanhoidichvu": "phản hồi dịch vụ",
    "phapche": "pháp chế",
    "phaply": "pháp lý",
    "phaplygiaothong": "pháp lý giao thông",
    "phapluat": "pháp luật",
    "phat": "phạt",
    "phatnguoi": "phạt nguội",
    "phattrien": "phát triển",
    "phattrienbenvung": "phát triển bền vững",
    "benvung": "bền vững",
    "pheduyet": "phê duyệt",
    "phieuluu": "phiêu lưu",
    "phongban": "phòng ban",
    "phongkinhdoanh": "phòng kinh doanh",
    "phongkythuat": "phòng kỹ thuật",
    "phongnhansu": "phòng nhân sự",
    "phongthamdinh": "phòng thẩm định",
    "phucvu": "phục vụ",
    "phuongtien": "phương tiện",
    "quanhe": "quan hệ",
    "quanly": "quản lý",
    "quantri": "quản trị",
    "quatang": "quà tặng",
    "quydautu": "quỹ đầu tư",
    "quytrinh": "quy trình",
    "baocao": "báo cáo",
    "xemxet": "xem xét",
    "riengtu": "riêng tư",
    "ruiro": "rủi ro",
    "sanpham": "sản phẩm",
    "sanphammoi": "sản phẩm mới",
    "sangtao": "sáng tạo",
    "sangkien": "sáng kiến",
    "saoluu": "sao lưu",
    "sathach": "sát hạch",
    "cuahang": "cửa hàng",
    "sieusale": "siêu sale",
    "thurac": "thư rác",
    "trangthai": "trạng thái",
    "sukien": "sự kiện",
    "taichinh": "tài chính",
    "taikhoan": "tài khoản",
    "tailieu": "tài liệu",
    "taisan": "tài sản",
    "tapdoan": "tập đoàn",
    "congnghe": "công nghệ",
    "thacmac": "thắc mắc",
    "thamdinh": "thẩm định",
    "thamvanphapluat": "thẩm vấn pháp luật",
    "thanhtoan": "thanh toán",
    "thanhtoanhoanhao": "thanh toán hoàn hảo",
    "hoanhao": "hoàn hảo",
    "thanhcong": "thành công",
    "thanhvien": "thành viên",
    "thanphien": "than phiền",
    "thaydoi": "thay đổi",
    "thitruong": "thị trường",
    "thoitrangdep": "thời trang đẹp",
    "thongbao": "thông báo",
    "thongbaochovay": "thông báo cho vay",
    "thongtin": "thông tin",
    "thuky": "thư ký",
    "thunghiem": "thử nghiệm",
    "thuongmai": "thương mại",
    "thutuc": "thủ tục",
    "thutucmuahang": "thủ tục mua hàng",
    "tienich": "tiện ích",
    "tienmat": "tiền mặt",
    "tiendohoso": "tiến độ hồ sơ",
    "tiepnhan": "tiếp nhận",
    "tindung": "tín dụng",
    "tinhtrang": "tình trạng",
    "tintuc": "tin tức",
    "toaan": "tòa án",
    "toanbo": "toàn bộ",
    "tochuc": "tổ chức",
    "tracuu": "tra cứu",
    "truongban": "trưởng ban",
    "truongnhom": "trưởng nhóm",
    "truycap": "truy cập",
    "tudohoc": "tự do học",
    "tudocanhan": "tự do cá nhân",
    "tuonglai": "tương lai",
    "tuvan": "tư vấn",
    "tuvankhoanvay": "tư vấn khoản vay",
    "tuvantaichinh": "tư vấn tài chính",
    "tuvanvay": "tư vấn vay",
    "tuvanvien": "tư vấn viên",
    "tuyendung": "tuyển dụng",
    "capnhat": "cập nhật",
    "uudai": "ưu đãi",
    "uudaidacbiet": "ưu đãi đặc biệt",
    "dacbiet": "đặc biệt",
    "uytin": "uy tín",
    "vande": "vấn đề",
    "vanchuyen": "vận chuyển",
    "vanphong": "văn phòng",
    "vanphongluat": "văn phòng luật",
    "vay": "vay",
    "vaynhanh": "vay nhanh",
    "vaysieutoc": "vay siêu tốc",
    "vaytien": "vay tiền",
    "vaytoan": "vay toàn",
    "vayvon": "vay vốn",
    "xacminh": "xác minh",
    "vip": "vip",
    "vipham": "vi phạm",
    "vuive": "vui vẻ",
    "websitechinh": "website chính",
    "xacnhan": "xác nhận",
    "xacnhandonhang": "xác nhận đơn hàng",
    "xacnhanvay": "xác nhận vay",
    "xemxethoso": "xem xét hồ sơ",
    "xemxet": "xem xét",
    "xuly": "xử lý",
    "xulyhosokho": "xử lý hồ sơ khó",
    "xulyvipham": "xử lý vi phạm",
    "ykien": "ý kiến",
    "ykienkhachhang": "ý kiến khách hàng",
    "yeucau": "yêu cầu"
}