NAMES_DICT = {}

CAR_BRANDS = {
    "Acura"                     : "A kiu ra",
    "Alfa Romeo"                : "An pha Rô mê ô",
    "Alpine"                    : "An pin",
    "Aston Martin"              : "Át tôn Mác tin",
    "Audi"                      : "Au đi",
    "Bentley"                   : "Ben ly",
    "BMW"                       : "Bi Em Đắp liu",
    "Bugatti"                   : "Bu ga ti",
    "Buick"                     : "Biu ích",
    "Cadillac"                  : "Ca đi lắc",
    "Chevrolet"                 : "Sép rô lê",
    "Chrysler"                  : "Cờ rai lơ",
    "Citroën"                   : "Xi trô en",
    "Dodge"                     : "Đót chơ",
    "Ferrari"                   : "Phê ra ri",
    "Fiat"                      : "Phi át",
    "Ford"                      : "Pho",
    "Genesis"                   : "Gie nơ xít",
    "GMC"                       : "Gi Em Xi",
    "Haval"                     : "Ha van",
    "Honda"                     : "Hon đa",
    "Hongqi"                    : "Hồng Kỳ",
    "Hyundai"                   : "Hyun đai",
    "Infiniti"                  : "In phi ni ti",
    "Isuzu"                     : "I su du",
    "Jaguar"                    : "Cha goa",
    "Jeep"                      : "Gíp",
    "Lamborghini"               : "Lam bo ghi ni",
    "Land Rover"                : "Len Rô vờ",
    "Lexus"                     : "Lếch xợt",
    "Lincoln"                   : "Lin côn",
    "Lynk & Co"                 : "Linh en Cô",
    "Maserati"                  : "Ma xơ ra ti",
    "Mazda"                     : "Mát đa",
    "McLaren"                   : "Mác La ren",
    "Mercedes Benz"             : "Mơ sây đì Ben",
    "Mercedes"                  : "Mơ sây đì",
    "MG"                        : "Em Gi",
    "Mini"                      : "Mi ni",
    "Mitsubishi"                : "Mít su bi shi",
    "Morgan"                    : "Mo gần",
    "Nissan"                    : "Nít xần",
    "Pagani"                    : "Pa ga ni",
    "Peugeot"                   : "Pơ giô",
    "Polestar"                  : "Pâu sta",
    "Porsche"                   : "Pót chơ",
    "Ram"                       : "Ram",
    "Renault"                   : "Rơ nô",
    "Rolls Royce"               : "Rôn roi",
    "Range Rover"               : "răng rô vơ",
    "SsangYong"                 : "Xang dong",
    "Subaru"                    : "Xu ba ru",
    "Suzuki"                    : "Su zu ki",
    "Tesla"                     : "Tét la",
    "Toyota"                    : "Tô yô ta",
    "VinFast"                   : "Vin Phát",
    "Volkswagen"                : "Vôn xoa gần",
    "Volvo"                     : "Vôn vô",
    "Wuling"                    : "Gu ling",
    "Abarth"                    : "A bát",
    "Koenigsegg"                : "Kô ních xéc",
    "Lucid"                     : "Lu xít",
    "Rimac"                     : "Ri mác",
    "Rivian"                    : "Ri vi an",
    "Wiesmann"                  : "Uy man",
    "Zenvo"                     : "Gien vô",
    "BYD"                       : "Bi Oai Đi",
    "Skoda"                     : "Skô đa",
    "Geely"                     : "Chi li",
    "Great Wall"                : "Grết Oôn",
    "Chery"                     : "Che ri",
    "Proton"                    : "Prô tôn",
}
NAMES_DICT.update(CAR_BRANDS)

CAR_TUNER_BRANDS = {
    "AMG"                       : "Ây Em Gi",
    "Brabus"                    : "Bờ ra bớt",
    "Mansory"                   : "Man so ri",
    "Maybach"                   : "May bách",
    "Nismo"                     : "Nít mô",
    "RUF"                       : "Rúp",
    "Hennessey"                 : "He ne xi",
    "DMC"                       : "Đi Em Xi",
    "Novitec"                   : "Nô vi téc",
    "Alpina"                    : "An pi na",
}
NAMES_DICT.update(CAR_TUNER_BRANDS)

TIRE_BRANDS = {
    "Bridgestone"               : "Bờ rít tôn",
    "Continental"               : "Con ti nen tồ",
    "Dunlop"                    : "Đun lốp",
    "Goodyear"                  : "Gút dia",
    "Michelin"                  : "Mi sơ lin",
    "Pirelli"                   : "Pi re li",
    "Hankook"                   : "Han cúc",
    "Kumho"                     : "Kum hô",
    "Maxxis"                    : "Mắc xít",
    "Yokohama"                  : "Yô cô ha ma",
}
NAMES_DICT.update(TIRE_BRANDS)

TECH_AND_OTHER_NAMES = {
    "4MATIC"                    : "Pho ma tích",
    "4x4"                       : "Bốn nhân bốn",
    "AWD"                       : "Ây Đắp liu Đi",
    "FWD"                       : "Ép Đắp liu Đi",
    "RWD"                       : "Ria Đắp liu Đi",
    "i-VTEC"                    : "Ai Vi téc",
    "Quattro"                   : "Quát trô",
    "Skyactiv"                  : "Skai ác típ",
    "TDI"                       : "Ti Đi Ai",
    "Turbo"                     : "Tuốc bô",
    "VTEC"                      : "Vi téc",
    "DOHC"                      : "Đi Ô Hát Xi",
    "SOHC"                      : "Ét Ô Hát Xi",
    "ABS"                       : "A Bi Ét",
    "ESP"                       : "E Ét Pi",
    "Supercharged"              : "Súp pơ sạc",
}
NAMES_DICT.update(TECH_AND_OTHER_NAMES)

MOTORCYCLE_BRANDS = {
    "Aprilia"                   : "A pri li a",
    "Benelli"                   : "Be ne li",
    "BMW Motorrad"              : "Bi Em Đắp liu Mô tô rát",
    "Brixton"                   : "Bờ rích tôn",
    "CFMoto"                    : "Xi ép Mô tô",
    "Ducati"                    : "Đu ca ti",
    "GasGas"                    : "Ga ga",
    "Harley Davidson"           : "Hác ly Đa vít sơn",
    "Husqvarna"                 : "Hút va na",
    "Indian Motorcycle"         : "In đi ần Mô tô sai cồ",
    "Kawasaki"                  : "Ka oa xa ki",
    "KTM"                       : "Kây Ti Em",
    "Kymco"                     : "Kim cô",
    "Moto Guzzi"                : "Mô tô Gút xi",
    "MV Agusta"                 : "Em Vi A gút ta",
    "Norton"                    : "No tơn",
    "Piaggio"                   : "Pi a gi ô",
    "Royal Enfield"             : "Roi ồ En phiu",
    "SYM"                       : "Ét Oai Em",
    "Triumph"                   : "Trai âm",
    "TVS"                       : "Ti Vi Ét",
    "Vespa"                     : "Vét pa",
    "Yamaha"                    : "Da ma ha",
    "NVX"                       : "En Vi Ích",
    "PG-1"                      : "Pê Gờ Một",
    "SH Mode"                   : "Ét Hắt Mốt",
    "Rebel"                     : "Rê bồ",
    "Exciter"                   : "Ếch xai tơ",
    "Wave RSX"                  : "Guây Rờ Ét Ích",
}
NAMES_DICT.update(MOTORCYCLE_BRANDS)

POPULAR_CAR_MODELS = {
    "Accent"                    : "Ác xen",
    "Airblade"                  : "E bờ lết",
    "Camry"                     : "Cam ri",
    "Carnival"                  : "Các ni van",
    "City"                      : "Xi ti",
    "Civic"                     : "Xi vích",
    "Corolla Altis"             : "Cô rô la An tít",
    "CR-V"                      : "Xê Rờ Vê",
    "Everest"                   : "E vơ rét",
    "Exciter"                   : "Ếch xai tơ",
    "Fadil"                     : "Pha đin",
    "Fortuner"                  : "Pho tu nơ",
    "Future"                    : "Phiu chờ",
    "Grande"                    : "Gờ ran đê",
    "i10"                       : "i mười",
    "Innova"                    : "In nô va",
    "Janus"                     : "Gia nút",
    "K3"                        : "Ka ba",
    "Lead"                      : "Lít",
    "Lux"                       : "Lắc",
    "Outlander"                 : "Ao len đơ",
    "President"                 : "Pờ re si đần",
    "Raider"                    : "Rai đơ",
    "Ranger"                    : "Ren giơ",
    "Santa Fe"                  : "San ta Phê",
    "Santafe"                   : "San ta Phê",
    "Satria"                    : "Sa tri a",
    "Seltos"                    : "Xen tốt",
    "SH"                        : "Ét hắt",
    "Sirius"                    : "Si ri ớt",
    "Sonet"                     : "Sô nét",
    "Triton"                    : "Trai từn",
    "Tucson"                    : "Túc sơn",
    "VF 1"                      : "Vê ép một",
    "VF 2"                      : "Vê ép hai",
    "VF 3"                      : "Vê ép ba",
    "VF 4"                      : "Vê ép bốn",
    "VF 5"                      : "Vê ép năm",
    "VF 6"                      : "Vê ép sáu",
    "VF 7"                      : "Vê ép bẩy",
    "VF 8"                      : "Vê ép tám",
    "VF 9"                      : "Vê ép chín",
    "VF e34"                    : "Vê ép e ba tư",
    "VF"                        : "Vê ép",
    "Vios"                      : "Vai ót",
    "Vision"                    : "Vi dừn",
    "Wave"                      : "guây",
    "Winner"                    : "Uyn nơ",
    "Xpander"                   : "Ích pan đơ",
    "3 Series"                  : "Ba xi ri",
    "5 Series"                  : "Năm xi ri",
    "7 Series"                  : "Bẩy xi ri",
    "911"                       : "Chín một một",
    "A-Class"                   : "Ây lát",
    "C-Class"                   : "Xi lát",
    "E-Class"                   : "I lát",
    "S-Class"                   : "Ét lát",
    "G-Class"                   : "Gi lát",
    "GLC"                       : "Gờ Lờ Xê",
    "GLE"                       : "Gờ Lờ E",
    "GLS"                       : "Gờ Lờ Ét",
    "Hilux"                     : "Hai lắc",
    "Land Cruiser"              : "Len Cru sơ",
    "Mustang"                   : "Mút tang",
    "RAV4"                      : "Ráp pho",
    "Wrangler"                  : "Rang lơ",
    "Creta"                     : "Cre ta",
    "Corolla Cross"             : "Cô rô la Cơ rốt",
    "CX-5"                      : "Xê Ích Năm",
    "HR-V"                      : "Hắt Rờ Vê",
    "Territory"                 : "Te ri to ri",
    "Veloz"                     : "Vê lót",
    "Verna"                     : "Véc na",
    "Wave Alpha"                : "Guây An pha",
    "Xforce"                    : "Ích phoóc",
    "Altis"                     : "An tít",
    "Accord"                    : "A co",
    "Mazda 3"                   : "Mát đa Ba",
    "Kona"                      : "Kô na",
    "Elantra"                   : "E lan tra",
    "Morning"                   : "Mo ninh",
    "Sorento"                   : "Sô ren tô",
    "Stargazer"                 : "Sta gây dơ",
    "Pajero Sport"              : "Pa giê rô Spót",
    "Navara"                    : "Na va ra",
    "Wigo"                      : "Uy gô",
    "Raize"                     : "Rai zơ",
    "Alphard"                   : "An phát",
    "Ranger Raptor"             : "Ren giơ Ráp tơ",
    "Transit"                   : "Tran zít",
    "Explorer"                  : "Ích plo rơ",
    "Taycan"                    : "Thai can",
    "Panamera"                  : "Pa na mê ra",
    "Macan"                     : "Ma can",
    "Cayenne"                   : "Cai en",
    "Boxster"                   : "Bóc tơ",
    "Cayman"                    : "Cai man",
    "Yaris"                     : "Ya rít",
}
NAMES_DICT.update(POPULAR_CAR_MODELS)

FOREIGN_TECH_COMPANIES = {
    "Apple"                 	: "Áp pồ",
    "Samsung"               	: "Sam sung",
    "Xiaomi"                	: "xi ao mi",
    "Oppo"                  	: "Ốp pô",
    "Vivo"                  	: "Vi vô",
    "Huawei"                	: "Hu uây",
    "Realme"                	: "Riêu mi",
    "Google"                	: "Gu gồ",
    "Sony"                  	: "Sô ni",
    "Asus"                  	: "a sút",
    "Nokia"                 	: "Nô ki a",
    "OnePlus"               	: "Oăn pờ lớt",
    "Motorola"              	: "Mô tô rô la",
    "Lenovo"                	: "Lê nô vô",
    "ZTE"                   	: "Zét Ti y",
    "Nothing"               	: "Na thing",
    "Dell"                  	: "Đeo",
    "HP"                    	: "hát pê",
    "Acer"                  	: "Ây sơ",
    "MSI"                   	: "Em Ét Ai",
    "Razer"                 	: "Rây dờ",
    "LG"                    	: "Eo Gi",
    "Microsoft Surface"     	: "Mai cờ rô sốp Sơ phây",
    "Gigabyte"              	: "Gi ga bai",
    "Nvidia"                    : "En vi di a",
    "Intel"                     : "In ten",
    "AMD"                       : "Ây Em Đi",
    "Qualcomm"                  : "Coan com",
    "TSMC"                      : "Ti Ét Em Xi",
    "Meta"                      : "Mê ta",
    "Amazon"                    : "A ma zôn",
    "Adobe"                     : "A đô bi",
    "Oracle"                    : "O ra cồ",
    "SAP"                       : "Ét A Pi",
    "Salesforce"                : "Xeo pho",
    "IBM"                       : "Ai Bi Em",
    "Cisco"                     : "Xít cô",
    "Tencent"                   : "Ten xen",
    "Alibaba"                   : "A li ba ba",
    "Baidu"                     : "Bai đu",
    "Nintendo"                  : "Nin ten đô",
    "PlayStation"               : "Play Sờ té sần",
    "Xbox"                      : "Ích bóc",
    "Openai"                    : "âu pừn ây ai",
}
NAMES_DICT.update(FOREIGN_TECH_COMPANIES)

VIETNAMESE_TECH_COMPANIES = {
    "Vietjet"                   : "Việt dét",
    "Vingroup"                  : "Vin gờ rúp",
    "GGroup"                    : "di gờ rúp",
    "SunGroup"                  : "săn gờ rúp",
    "VNDirect"                  : "Vi en đai rếch",
    "VN-Index"                  : "Vi en in đếch",
    "VNG"                       : "Vi en gi",
    "CMC"                       : "Xi em xi",
    "MISA"                      : "Mi sa",
    "Bkav"                      : "Bê ca a vê",
    "VCCorp"                    : "Vê xê cóp",
    "MoMo"                      : "Mô mô",
    "ZaloPay"                   : "Gia lô pây",
    "Grab"                      : "Gờ ráp",
    "Shopee"                    : "Sóp pi",
    "ShopeeFood"                : "Sóp pi phút",
    "Shopee Food"               : "Sóp pi phút",
    "Lazada"                    : "La da đa",
    "GoJek"                     : "Gô giếch",
    "Tiki"                      : "Ti ki",
    "Fsoft"                     : "ép sóp",
    "F-soft"                    : "ép sóp",
    "Viettel"                   : "Việt theo",
    "Vinafone"                  : "Vi na phôn",
    "Mobifone"                  : "Mô bi phôn",
    "VNPT"                      : "Vi en pi ti",
    "FPT"                       : "Ép Pi Ti",
    "VNPay"                     : "Vi En Pây",
    "Sendo"                     : "Sen đô",
    "Foody"                     : "Phu đi",
    "Be"                        : "Be",
    "Ahamove"                   : "A ha mu",
    "ELSA Speak"                : "En sa Spík",
    "TopCV"                     : "Tóp Xi Vi",
    "Thegioididong"             : "Thế giới di động",
    "FPT Shop"                  : "Ép Pi Ti Sóp",
    "Cellphones"                : "Sen pho Ét",
    "Nguyen Kim"                : "Nguyễn Kim",
    "Dien May Xanh"             : "Điện Máy Xanh",
    "Phuc Long"                 : "Phúc Long",
    "Highlands Coffee"          : "Hai len Cóp phi",
    "Cong Caphe"                : "Cộng Ca phê",
    "The Coffee House"          : "Dờ Cóp phi Hao",
    "Mixue"                     : "Mích xuê",
    "Coolmate"                  : "Cun mét",
    "Yody"                      : "Yô đi",
    "Canifa"                    : "Ca ni fa",
    "Owen"                      : "Ô uen",
    "Aristino"                  : "A rít ti nô",
    "Routine"                   : "Ru tin",
    "DirtyCoins"                : "Đơ ti Coin",
    "Bitis Hunter"              : "Bi tít Han tơ",
    "Ananas"                    : "A na nát",
    "Vascara"                   : "Vát ca ra",
    "Juno"                      : "Giu nô",
    "PREP"                      : "pở rép",
}
NAMES_DICT.update(VIETNAMESE_TECH_COMPANIES)

SOCIAL_MEDIA_APPS = {
    "Facebook"                  : "Phây búc",
    "Zalo"                      : "Da lô",
    "TikTok"                    : "Tích tốc",
    "Instagram"                 : "In ta gờ ram",
    "YouTube"                   : "Diu túp",
    "Messenger"                 : "Mét sen giơ",
    "Telegram"                  : "Tê lê gờ ram",
    "Pinterest"                 : "Pin tơ rét",
    "LinkedIn"                  : "Linh in",
    "Twitter"                   : "Tuýt tơ",
    "Threads"                   : "Thờ rét",
    "WhatsApp"                  : "Goát áp",
    "Viber"                     : "Vai bơ",
    "Discord"                   : "Đít cót",
    "Snapchat"                  : "Sờ náp chát",
    "Story"                     : "Sờ to ry",
    "Reddit"                    : "Rét đít",
    "Tumblr"                    : "Tăm bơ",
    "Flickr"                    : "Flích cờ",
    "Vimeo"                     : "Vi meo",
    "Twitch"                    : "Tuých",
    "Clubhouse"                 : "Cờ láp hao",
    "Mastodon"                  : "Mát tô đon",
    "Bluesky"                   : "Bờ lu skai",
    "WeChat"                    : "Uy chát",
    "Line"                      : "Lai",
    "KakaoTalk"                 : "Ca cao Tóc",
    "QQ"                        : "Q Q",
    "Weibo"                     : "Uy bô",
    "Douyin"                    : "Đâu yin",
    "Kuaishou"                  : "Khoai sô",
    "X"                         : "Ích",
    "Slack"                     : "Sờ lách",
}
NAMES_DICT.update(SOCIAL_MEDIA_APPS)

OTHER_APPS = {
    "CapCut"                    : "Cap cắt",
    "VNeID"                     : "Vi en i ai đi",
    "VssID"                     : "Vi ét ét ai đi",
    "ChatGPT"                   : "Chát Gi pi ti",
    "Google Meet"               : "Gu gồ Mít",
    "Zoom"                      : "Dum",
    "Spotify"                   : "Sờ pót ti phai",
    "Netflix"                   : "Nét phờ lích",
    "VieON"                     : "Vi on",
    "Xanh SM"                   : "Xanh ét em",
    "Canva"                     : "Can va",
    "Picsart"                   : "Pích át",
    "Photoshop"                 : "Phô tô sốp",
    "Teams"                     : "Tim",
    "Soundcloud"                : "sao cờ lao",
    "VTVGo"                     : "Vê tê vê gâu",
    "Google Maps"               : "Gu gồ Máp",
    "Google Photos"             : "Gu gồ Phô tô",
    "Google Drive"              : "Gu gồ Đrai",
    "Microsoft Word"            : "Mai cờ rô sốp Quật",
    "Microsoft Excel"           : "Mai cờ rô sốp Éc xen",
    "Adobe Acrobat"             : "A đô bi Ác rô bát",
    "Adobe Premiere Pro"        : "A đô bi Pờ rê mia Pờ rô",
    "Lightroom"                 : "Lai rôm",
    "Figma"                     : "Fích ma",
    "Skype"                     : "Skai",
    "VLC Media Player"          : "Vi Eo Xi Mi đi a Pờ lay ơ",
    "WinRAR"                    : "Win Ra",
    "OBS Studio"                : "Ô Bi Ét Stu đi ô",
    "Zing MP3"                  : "dinh mờ pê ba",
}
NAMES_DICT.update(OTHER_APPS)

ENGLISH_TERMS = {
    "IELTS"                     : "ai eo",
    "TOEFL"                     : "Tô phồ",
    "SAT"                       : "Ét A Ti",
    "CEO"                       : "Xi I Ô",
    "IoT"                       : "Ai Ô Ti",
    "API"                       : "Ây Pi Ai",
    "HTTP"                      : "Hát Ti Ti Pi",
    "HTTPS"                     : "Hát Ti Ti Pi Ét",
    "URL"                       : "Yu A Rờ Eo",
    "HTML"                      : "Hát Ti Em Eo",
    "CSS"                       : "Xi Ét Ét",
    "JS"                        : "Gi Ét",
    "SQL"                       : "Ét Qun Eo",
    "JSON"                      : "Giây Xon",
    "PDF"                       : "Pi Đi Ép",
    "MP3"                       : "Em Pi Ba",
    "MP4"                       : "Em Pi Bốn",
    "Python"                    : "Pai thon",
    "Java"                      : "Gia va",
    "C#"                        : "Xi Sáp",
    "C++"                       : "Xi Plút Plút",
    "React"                     : "Ri ác",
    "Angular"                   : "En gu lơ",
    "Node.js"                   : "Nốt Gi Ét",
    "Docker"                    : "Đóc kơ",
    "Git"                       : "Gít",
    "TOIEC"                     : "tô ích",
}
NAMES_DICT.update(ENGLISH_TERMS)

GAMES = {
    "Liên Quân Mobile"          : "Liên quân mô bai",
    "PUBG"                      : "Pắp gi",
    "Free Fire"                 : "Phờ ri phai",
    "League of Legends"         : "Lích ợp Le dần",
    "Valorant"                  : "Va lo ran",
    "CS:GO"                     : "Xi Ét Gô",
    "Dota 2"                    : "Đô ta Hai",
    "Minecraft"                 : "Mai cờ ráp",
    "Fortnite"                  : "Fót nai",
    "Apex Legends"              : "Ây péc Le dần",
    "Call of Duty"              : "Co ợp Điu ti",
    "Grand Theft Auto"          : "Gờ ran Thép Au tô",
    "FIFA"                      : "Fi fa",
    "Pokémon"                   : "Pô kê mon",
    "Genshin Impact"            : "Gen sin Im pắc",
    "Mobile Legends: Bang Bang" : "Mô bai Le dần Bang Bang",
    "Clash of Clans"            : "Cờ lát ợp Clan",
    "Brawl Stars"               : "Bờ rau Sta",
    "Roblox"                    : "Rô lốc",
}
NAMES_DICT.update(GAMES)

COMPUTER_TERMS = {
    "GPU"                       : "Di pi u",
    "RAM"                       : "Ra Em",
    "SSD"                       : "Ét Ét Đi",
    "HDD"                       : "Hát Đi Đi",
    "USB"                       : "Yu Ét Bi",
    "HDMI"                      : "Hát Đi Em Ai",
    "BIOS"                      : "Bai ót",
    "Windows"                   : "Win đơ",
    "Linux"                     : "Li nắc",
    "Android"                   : "En đờ roi",
    "iOS"                       : "Ai Ô Ét",
    "Wi-Fi"                     : "Quai fai",
    "Bluetooth"                 : "Bờ lu tút",
    "Router"                    : "Rau tơ",
    "Modem"                     : "Mô đem",
    "Antivirus"                 : "En ti vai rút",
    "Malware"                   : "Man que",
    "Server"                    : "Sơ vơ",
    "Client"                    : "Cờ lai ần",
    "Internet"                  : "In tơ nét",
    "Cloud Computing"           : "Cờ lao Com pu ting",
    "CPU"                       : "Ci pi u",
}
NAMES_DICT.update(COMPUTER_TERMS)

FASHION_BRANDS = {
    "Vaio"                  	: "Vai ô",
    "Uniqlo"                	: "U ni khờ lô",
    "Zara"                  	: "Za ra",
    "H&M"                   	: "Ét en em",
    "GAP"                   	: "Gáp",
    "Old Navy"              	: "Âu Nây vi",
    "Topshop"               	: "Tóp sóp",
    "Topman"                	: "Tóp man",
    "Mango"                 	: "Man gô",
    "Pull&Bear"             	: "Pun en Be",
    "Stradivarius"          	: "xờ tra đi va ri út",
    "Bershka"               	: "Bếch xờ ka",
    "Levi's"                	: "Li vai",
    "Adidas"                	: "A đi đát",
    "Nike"                  	: "Nai kì",
    "Puma"                  	: "Pu ma",
    "Converse"              	: "Con vớt",
    "Vans"                  	: "Van",
    "The North Face"        	: "dờ Nót Phây",
    "Lacoste"               	: "La cót",
    "Tommy Hilfiger"        	: "Tôm my Hiu phai gờ",
    "Louis Vuitton"         	: "Lu y Vuy tông",
    "Chanel"                	: "Cha neo",
    "Gucci"                 	: "Gu chì",
    "Dior"                  	: "Đi o",
    "Hermès"                	: "Hơ mét",
    "Prada"                 	: "Pờ ra đa",
    "Burberry"              	: "Bơ bơ ry",
    "Versace"               	: "Vơ sa chì",
    "Balenciaga"            	: "Ba len xi a gà",
    "Saint Laurent"         	: "Sanh Lo ron",
    "Givenchy"              	: "Gi von chì",
    "Fendi"                 	: "Phen đi",
    "Bvlgari"               	: "Bun ga ri",
    "Cartier"               	: "Các ti ê",
    "Rolex"                 	: "Rô lếch",
    "Omega"                 	: "Ô mê ga",
    "Christian Louboutin"   	: "Cờ rít chần Lu bu tanh",
    "Alexander McQueen"     	: "A lếch xan đơ Mạc Cuyn",
    "Patek Philippe"        	: "Pa téc Phi líp",
    "Audemars Piguet"       	: "O đơ ma Pi ghê",
    "Longines"              	: "Lon gin",
    "Tissot"                	: "Tít sô",
    "TAG Heuer"             	: "Thác Hoi ơ",
    "Hublot"                	: "Húp lô",
    "IWC Schaffhausen"      	: "Ai Đắp liu xi Sáp hao sần",
    "Jaeger LeCoultre"      	: "Yê gơ Lơ Cut",
    "Vacheron Constantin"   	: "Va sơ ron Con xtan tin",
    "Breitling"             	: "Bờ rai ling",
    "Zenith"                	: "dê nít",
    "Rado"                  	: "Ra đô",
    "Mido"                  	: "Mi đô",
    "Hamilton"              	: "Ha min tơn",
    "Seiko"                 	: "Sây cô",
    "Citizen"               	: "Xi ti zần",
    "Casio"                 	: "Ca si ô",
    "Orient"                	: "O ri en",
    "Grand Seiko"           	: "Gờ ran Sây cô",
    "A. Lange & Söhne"      	: "A Lang gơ un Sô nơ",
    "Glashütte Original"    	: "Gờ lát su tờ O ri gi nan",
    "Nomos Glashütte"       	: "Nô mốt Gờ lát su tờ",
    "Sinn"                  	: "Zin",
    "Bulova"                	: "Bu lô va",
    "MVMT"                  	: "Mu vờ mần",
    "Daniel Wellington"     	: "Đa ni ồ Que linh tân",
    "Forever 21"                : "Fo re vơ Hai mươi mốt",
    "American Eagle"            : "A me ri cờ I gồ",
    "Victoria's Secret"         : "Víc to ri a Xích rét",
    "Sephora"                   : "Se pho ra",
    "MAC Cosmetics"             : "Mác Cót me tíc",
    "Estée Lauder"              : "Ét ti Lo đơ",
    "Clinique"                  : "Cờ li ních",
    "L'Oréal"                   : "Lo reo",
    "Maybelline"                : "Mây bơ lin",
    "Revlon"                    : "Rép lon",
    "Fenty Beauty"              : "Fen ti Biu ti",
    "Jo Malone London"          : "Giô Ma lon Lon đon",
    "Byredo"                    : "Bai re đô",
    "Le Labo"                   : "Lơ La bô",
    "Diptyque"                  : "Đíp tích",
    "Creed"                     : "Cờ rít",
    "Fossil"                	: "Phó xồ",
}
NAMES_DICT.update(FASHION_BRANDS)

FOOTBALL_TEAMS = {
    "Manchester United"     	: "Man chét tơ Du nai tịch",
    "Manchester City"       	: "Man chét tơ Xi ti",
    "Liverpool"             	: "Li vơ pun",
    "Arsenal"               	: "Ác xê nan",
    "Chelsea"               	: "Chen xi",
    "Tottenham Hotspur"     	: "Tốt tân ham Hót pơ",
    "Newcastle United"      	: "Niu cát xồ Du nai tịch",
    "Aston Villa"           	: "Át xờ tôn Vi la",
    "Everton"               	: "Ê vơ tơn",
    "West Ham United"       	: "Oét Ham Du nai tịch",
    "Real Madrid"           	: "Rê an Ma rít",
    "Barcelona"             	: "Bác xê lô na",
    "Atlético Madrid"       	: "Át lê ti cô Ma rít",
    "Sevilla"               	: "Xê vi a",
    "Villarreal"            	: "Vi la rê an",
    "Real Sociedad"         	: "Rê an Xô xi ê đát",
    "Athletic Bilbao"       	: "Át lê tích Bin bao",
    "Juventus"              	: "Du ven tút",
    "AC Milan"              	: "Ây xi Mi lan",
    "Inter Milan"           	: "In tơ Mi lan",
    "Napoli"                	: "Na pô li",
    "AS Roma"               	: "Ây ét Rô ma",
    "Lazio"                 	: "La zi ô",
    "Atalanta"              	: "A ta lan ta",
    "Bayern Munich"         	: "Bai en Muy ních",
    "Borussia Dortmund"     	: "Bô rút xi a Đót mun",
    "RB Leipzig"            	: "A Bi Lép zịch",
    "Bayer Leverkusen"      	: "Bai ơ Lê vơ cu sần",
    "Eintracht Frankfurt"   	: "A in trát Phờ rang phuốc",
    "Paris Saint Germain"   	: "Pa ri Sanh déc manh",
    "Olympique de Marseille"	: "Ô lim pích đờ Mác xây",
    "AS Monaco"             	: "Ây ét Mô na cô",
    "Olympique Lyonnais"    	: "Ô lim pích Li ông",
    "Ajax"                  	: "A dắc",
    "Porto"                 	: "Póc tô",
    "Benfica"               	: "Ben phi ca",
    "Al Nassr"              	: "An Na xơ",
    "Inter Miami"           	: "In tơ Mai a mi",
    "Boca Juniors"          	: "Bô ca Du ni o",
    "Borussia Mönchengladbach"  : "Bô rút xi a Mơn chen gờ lát bách",
    "Schalke 04"                : "San ke Không bốn",
    "Hamburger SV"              : "Ham bơ gơ Ét Vê",
    "Werder Bremen"             : "Ve đơ Bờ rê men",
    "VfB Stuttgart"             : "Vê ép Bi Sút gát",
    "1. FC Köln"                : "Một Ép Xi Cơn",
    "Hertha BSC"                : "Hơ tha Bi Ét Xi",
    "Feyenoord"                 : "Fay nơ ót",
    "PSV Eindhoven"             : "Pi Ét Vê An hô ven",
    "Sporting CP"               : "Sờ pót ting Xi Pi",
    "Galatasaray"               : "Ga la ta rai",
    "Fenerbahçe"                : "Fe nơ ba chơ",
    "Beşiktaş"                  : "Be sít tát",
    "Olympiacos"                : "Ô lim pi a cót",
    "Panathinaikos"             : "Pa na thi nai cót",
    "Celtic"                    : "Sen tíc",
    "Rangers"                   : "Ren giơ",
    "River Plate"           	: "Ri vơ Pờ lết",
}
NAMES_DICT.update(FOOTBALL_TEAMS)

BANKS = {
    "ACB"                       : "A xê bê",
    "Agribank"                  : "A gờ ri banh",
    "BIDV"                      : "Bi ai đi vi",
    "CBBank"                    : "Xi bi banh",
    "Eximbank"                  : "E xim banh",
    "GPBank"                    : "Gi pi banh",
    "HDBank"                    : "Hắt đê banh",
    "HSBC"                      : "Hắt ét bi xi",
    "KienlongBank"              : "Kiên long banh",
    "LPBank"                    : "Lờ pê banh",
    "MB"                        : "Mờ bê",
    "MSB"                       : "Mờ ét bê",
    "Nam A Bank"                : "Nam á banh",
    "NCB"                       : "En xi bi",
    "OCB"                       : "Ô xi bi",
    "OceanBank"                 : "Ô sần banh",
    "PG Bank"                   : "Pê gờ banh",
    "PVcomBank"                 : "Pê vê com banh",
    "Sacombank"                 : "Sa com banh",
    "Saigonbank"                : "Sài gòn banh",
    "SCB"                       : "Ét xi bi",
    "SeABank"                   : "Xi a banh",
    "SHB"                       : "Ét hắt bê",
    "TCB"                       : "Tếch com banh",
    "TPBank"                    : "Ti pi banh",
    "VIB"                       : "Vi ai bi",
    "VietABank"                 : "Việt á banh",
    "Vietcombank"               : "Việt com banh",
    "VCB"                       : "Việt com banh",
    "VietinBank"                : "Việt tin banh",
    "DongA Bank"                : "Đông Á banh",
    "Viet Capital Bank"         : "Việt Ca pi tồ banh",
    "BaoViet Bank"              : "Bảo Việt banh",
    "Indovina Bank"             : "In đô vi na banh",
    "Shinhan Bank"              : "Sin han banh",
    "Woori Bank"                : "U ri banh",
    "Standard Chartered"        : "Stan đát Cha tợt",
    "ANZ"                       : "En Zét",
    "Citi"                      : "Xi ti",
    "Deutsche Bank"             : "Đoi chơ banh",
    "BNP Paribas"               : "Bi En Pi Pa ri ba",
    "Mizuho Bank"               : "Mi zu hô banh",
    "UOB"                       : "Yu Ô Bi",
    "DBS Bank"                  : "Đi Bi Ét banh",
    "Maybank"                   : "Mây banh",
    "Public Bank"               : "Pắp lích banh",
    "CIMB Bank"                 : "Xi Em Bi banh",
    "Bangkok Bank"              : "Bang cóc banh",
    "Kasikornbank"              : "Ca xi co banh",
    "Bank of China"             : "Banh ợp Chai na",
    "ICBC"                      : "Ai Xi Bi Xi",
    "JPMorgan Chase"            : "Giây Pi Mo gân Chết",
    "Bank of America"           : "Banh ợp A me ri ca",
    "Wells Fargo"               : "Quen Pha gô",
    "Goldman Sachs"             : "Gôn man Sách",
    "Morgan Stanley"            : "Mo gân Sờ tan ly",
    "VPBank"                    : "Vi pi banh",
}
NAMES_DICT.update(BANKS)

GOLD_NAMES = {
    "SJC"                       : "Ét Giây Xi",
    "PNJ"                       : "Pi En Giây",
    "DOJI"                      : "Đô Gi",
    "Vàng 9999"                 : "Vàng bốn số chín",
    "Vàng 24K"                  : "Vàng hai tư ca",
    "Vàng 18K"                  : "Vàng mười tám ca",
}
NAMES_DICT.update(GOLD_NAMES)

FAMOUS_TOWERS = {
    "Landmark 81"               : "Len mác Tám mốt",
    "Keangnam Landmark 72"      : "Cang nam Len mác Bẩy hai",
    "Bitexco Financial Tower"   : "Bi téc co Phai nan sồ Tao",
    "Lotte Center"              : "Lót te Sen tơ",
    "Petronas Towers"           : "Pét rô na Tao",
    "Burj Khalifa"              : "Bớt Kha li fa",
    "Eiffel Tower"              : "Ép fen Tao",
    "Tokyo Skytree"             : "Tô ki ô Sờ cai tri",
    "Shanghai Tower"            : "San hai Tao",
    "Taipei 101"                : "Tai pây Một không một",
    "Willis Tower"              : "Uy lít Tao",
    "CN Tower"                  : "Xi En Tao",
}
NAMES_DICT.update(FAMOUS_TOWERS)

RESIDENTIAL_AREAS = {
    "Vinhomes"                  : "Vin hôm",
    "Ecopark"                   : "E cô pác",
    "Ciputra"                   : "Xi pu tra",
    "Phu My Hung"               : "Phú Mỹ Hưng",
    "Sala"                      : "Sa la",
    "Masterise Homes"           : "Mát tơ rai Hôm",
    "Novaland"                  : "Nô va len",
    "Sunshine City"             : "Săn sai Xi ti",
    "Gamuda City"               : "Ga mu đa Xi ti",
    "Celadon City"              : "Xê la đon Xi ti",
    "Mizuki Park"               : "Mi zu ki Pác",
    "Akari City"                : "A ca ri Xi ti",
    "Waterpoint"                : "Quo tơ poi",
    "SwanBay"                   : "Suan Bay",
    "SwanPark"                  : "Suan Pác",
}
NAMES_DICT.update(RESIDENTIAL_AREAS)
