VERBATIM = {
    '<=>' : ' tương đương ',
    '=>' : ' suy ra ',
    '#' : ' thăng ',
    '$' : ' đô la ',
    '%' : ' phần trăm ',
    '&' : ' và ',
    '+' : ' cộng ',
    '*' : ' nhân ',
    '<' : ' nhỏ hơn ',
    '=' : ' bằng ',
    '>' : ' lớn hơn ',
    '@' : ' a còng ',
    '^' : ' mũ ',
    'π' : ' pi ',
}